#!/bin/sh
# helper script to generate sunxi-overlays-builtin.inc
OFILE="sunxi-overlays-builtin.inc"
echo "# generated by gen_builtin.sh" > $OFILE
for famd in $(ls -1d files/*/); do
   fam=${famd##files/}
   fam=${fam%%/}
   echo "SRC_URI:${fam} = \" \\" >> $OFILE
   for f in $(ls ${famd}*.dts); do
	   echo "file://$(basename $f) \\" >> $OFILE
   done
   echo "\"" >> $OFILE
   families="$families|$fam"
done

families=${families#|}
echo "COMPATIBLE_MACHINE = \"(${families})\"" >> $OFILE

