#@TYPE: Machine
#@NAME: orange-pi-zero-3
#@DESCRIPTION: Machine configuration for the orange-pi-zero-3, based on Allwinner H618 CPU

require conf/machine/include/sun50i-h616.inc

KERNEL_DEVICETREE = "allwinner/sun50i-h618-orangepi-zero3.dtb"
IMAGE_BOOT_FILES = "${KERNEL_IMAGETYPE} boot.scr ${@d.getVar('KERNEL_DEVICETREE', '').split('/')[-1]};${KERNEL_DEVICETREE}}"
UBOOT_MACHINE = "orangepi_zero3_defconfig"

SPL_BINARY = "u-boot-sunxi-with-spl.bin"

SUNXI_BOOT_SPACE = "50"

# as for now neither graphics nor audio is supported
MACHINE_FEATURES:remove = "alsa x11"
MACHINE_FEATURES:append = "bluetooth wifi"

MACHINE_EXTRA_RRECOMMENDS = "uwe5622-firmware"

# Load modules for wifi & bt
# Note: fo wifi a custom hci attach userspace sofware is needed that is not included in the layer
KERNEL_MODULE_AUTOLOAD += " sprdwl_ng sprdbt_tty "

